sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: U7gBL4rC+V8kNWkFj3bdxNGX/qzM+31kj57HPuLSugwdnqlI9Y7+ZjJ2117BREJbs+1yjZS8hXYt2lha7q2R96aGNQDO6gPFF2EWRZztrnxy8cIP/KV6iESMIIv/H2giJABzC+/ZB+heuKDIcpMoJ420UNYqDR2kk4VcK60Z11gvUgZgcxwoW8AyTiWZTBVeywYHZNgAtqfosLDOlLOHDqm0MQDQ4uOCPXOop27g18pWOSqVRxXNTItdbZduu0EiEi97DDFqnCuE10oJkKGKbbhsQfapPMii1vYzCL0xJ3jrhf4sssx0aSqnGyp1/hNv2Y8KzGuuehuDuYTKXj9f29eMEQ5MeVmMldHT0zFbmfHy9uNwJrUjR7bYuVoawxBYAnt2tYWgO+L36vX9YcWb2cyPtmFqVe+KJmek97Z1AfMitcCwSNFZgUXppFGpAganU6z9vpFnzadaVY8Fw8HY2ZlJs9wUWwYAbYeJTG0GLKJa2eWoBRgfsS+9j6nTYhbPj4EypGfe2KeHgmrqCOtQqj0Iv0WJw7Vy7u2QNZd58hHTCAam8ntPHYgZ+W0x5YHBorIcebZRdA56aziG7IDYNRUQSSOmCyPx6Qu2U8yltuR/DBWuc+NaLLjUblZCo0xesEyZsPQ/OayVY/XzdR+Vd+yP3mkb8uKnZdTfNbjyLlc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Les-Chansons-De-Bilitis_4708
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy